// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createMockSupabaseClient } from './mock';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined || "https://xvwtxobrztdepzxveyrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2d3R4b2JyenRkZXB6eHZleXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwOTY1MTgsImV4cCI6MjA3ODY3MjUxOH0.TutIDKkw_YWXQlgGBXIFFKiOc0fzpmJKJ7juDSytns8";
const offlineModeEnv = (import.meta.env.VITE_OFFLINE_MODE as string | undefined)?.toLowerCase();
const OFFLINE_MODE =
  offlineModeEnv === "false"
    ? false
    : true;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const shouldUseMock =
  OFFLINE_MODE ||
  !SUPABASE_URL ||
  !SUPABASE_PUBLISHABLE_KEY ||
  SUPABASE_URL.trim() === "" ||
  SUPABASE_PUBLISHABLE_KEY.trim() === "";

export const supabase =
  shouldUseMock
    ? createMockSupabaseClient()
    : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      });